{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "typo3.fullname" . }}
  labels:
    {{- include "typo3.componentLabels" (dict "ctx" . "component" "app") | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "typo3.selectorLabels" (dict "ctx" . "component" "app") | nindent 6 }}
{{- end }}
